import { Language } from '../types';

export interface Translations {
  // Common
  appName: string;
  appSubtitle: string;
  save: string;
  cancel: string;
  delete: string;
  edit: string;
  close: string;
  search: string;
  searchPlaceholder: string;
  filter: string;
  all: string;
  actions: string;
  print: string;
  downloadPdf: string;
  shareWhatsApp: string;
  status: string;
  date: string;
  deliveryDate: string;
  returnDate: string;
  created: string;
  notes: string;
  details: string;
  back: string;
  yes: string;
  no: string;
  loading: string;
  success: string;
  savedSuccessfully: string;
  deletedSuccessfully: string;
  confirmDelete: string;
  areYouSure: string;
  noDataFound: string;
  viewDetails: string;
  required: string;
  optional: string;

  // Nav tabs
  dashboard: string;
  newOrder: string;
  customers: string;
  designAndSettings: string;
  designTemplatesNav: string;
  measurementSettingsNav: string;
  shopProfileNav: string;
  backupNav: string;
  menu: string;

  // Dashboard stats
  totalOrders: string;
  pendingOrders: string;
  inProgressOrders: string;
  readyOrders: string;
  deliveredOrders: string;
  totalRevenue: string;
  totalPaid: string;
  totalBalanceDue: string;

  // Order status
  statusPending: string;
  statusInProgress: string;
  statusReady: string;
  statusDelivered: string;

  // Payment status
  paymentStatus: string;
  paid: string;
  partial: string;
  unpaid: string;
  totalAmount: string;
  paidAmount: string;
  balanceRemaining: string;
  advancePayment: string;
  updatePayment: string;

  // Order Form
  customerInfo: string;
  customerName: string;
  contactNumber: string;
  whatsappNumber: string;
  orderNumber: string;
  autoGenerated: string;
  garmentType: string;
  quantity: string;
  orderSummary: string;
  measurements: string;
  designAndStyle: string;
  specialNotes: string;
  cabinetSlot: string;
  saveOrder: string;
  saveAndPrint: string;
  loadCustomerMeasurements: string;
  existingCustomerFound: string;
  newCustomerAutoSaved: string;
  quickFill: string;

  // Garment Types
  perahanTunban: string;
  waistcoat: string;
  suit: string;
  coatKorti: string;
  kameezShalwar: string;
  kurta: string;
  otherGarment: string;

  // Measurements labels
  qad: string; // قد (Length)
  shana: string; // شانه (Shoulder)
  asteen: string; // آستین (Sleeve)
  yakhan: string; // یخن / کالر (Collar/Neck)
  chati: string; // چاتی / سینه (Chest)
  baghal: string; // بغل (Armpit/Underarm)
  kamar: string; // کمر (Waist)
  daman: string; // دامن (Hem/Daman)
  tunban: string; // تنبان / پرتوګ (Trouser Length)
  pacha: string; // پاچه (Trouser Bottom)
  surin: string; // سورین (Hip/Seat)
  machDast: string; // مچ دست (Wrist)
  unitInches: string;

  // Customers View
  customersList: string;
  customerProfile: string;
  totalOrdersCount: string;
  lastOrderDate: string;
  savedMeasurements: string;
  createNewOrderForCustomer: string;
  customerHistory: string;
  searchCustomersPlaceholder: string;
  addNewCustomer: string;
  editCustomer: string;

  // Design Templates & Settings
  designTemplates: string;
  manageDesignCategories: string;
  addCategory: string;
  categoryTitle: string;
  addOption: string;
  optionName: string;
  measurementSettings: string;
  addMeasurementField: string;
  shopProfile: string;
  shopName: string;
  shopAddress: string;
  phones: string;
  receiptFooter: string;
  currency: string;
  backupAndRestore: string;
  exportBackup: string;
  importBackup: string;
  resetDemoData: string;
  backupDescription: string;

  // Receipt / Slip
  tailorReceipt: string;
  measurementSlip: string;
  billBarcode: string;
  phoneBarcode: string;
  item: string;
  qty: string;
  price: string;
  thankYouMessage: string;

  // Login & Auth
  loginTitle: string;
  loginSubtitle: string;
  email: string;
  password: string;
  signInBtn: string;
  signOut: string;
  invalidCredentials: string;
  quickLoginAdmin: string;
  loggedInAs: string;
  adminAccount: string;
}

export const translations: Record<Language, Translations> = {
  en: {
    appName: 'Rayan Tailor Shop Management',
    appSubtitle: 'Orders, Measurements & Customer Management',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    search: 'Search',
    searchPlaceholder: 'Search by Order #, Customer Name, or Phone...',
    filter: 'Filter',
    all: 'All',
    actions: 'Actions',
    print: 'Print Slip',
    downloadPdf: 'Download PDF',
    shareWhatsApp: 'Send via WhatsApp',
    status: 'Status',
    date: 'Date',
    deliveryDate: 'Delivery Date',
    returnDate: 'Return Date',
    created: 'Created',
    notes: 'Notes',
    details: 'Details',
    back: 'Back',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading...',
    success: 'Success',
    savedSuccessfully: 'Saved successfully',
    deletedSuccessfully: 'Deleted successfully',
    confirmDelete: 'Are you sure you want to delete this record?',
    areYouSure: 'This action cannot be undone.',
    noDataFound: 'No records found',
    viewDetails: 'View Details',
    required: 'Required',
    optional: 'Optional',

    dashboard: 'Orders Dashboard',
    newOrder: 'New Order',
    customers: 'Customer Directory',
    designAndSettings: 'Design & Settings',
    designTemplatesNav: 'Design Templates',
    measurementSettingsNav: 'Measurement Fields',
    shopProfileNav: 'Shop Profile & Slip',
    backupNav: 'Backup & Restore',
    menu: 'Main Navigation',

    totalOrders: 'Total Orders',
    pendingOrders: 'Pending',
    inProgressOrders: 'In Progress',
    readyOrders: 'Ready for Pickup',
    deliveredOrders: 'Delivered / Completed',
    totalRevenue: 'Total Value',
    totalPaid: 'Collected Paid',
    totalBalanceDue: 'Balance Due',

    statusPending: 'Pending',
    statusInProgress: 'In Stitching',
    statusReady: 'Ready for Pickup',
    statusDelivered: 'Delivered',

    paymentStatus: 'Payment Status',
    paid: 'Paid in Full',
    partial: 'Partial / Advance',
    unpaid: 'Unpaid',
    totalAmount: 'Total Amount',
    paidAmount: 'Paid / Advance',
    balanceRemaining: 'Remaining Balance',
    advancePayment: 'Advance Payment',
    updatePayment: 'Update Payment',

    customerInfo: 'Customer Information',
    customerName: 'Customer Name',
    contactNumber: 'Phone / Contact Number',
    whatsappNumber: 'WhatsApp Number',
    orderNumber: 'Order Number',
    autoGenerated: 'Auto-generated',
    garmentType: 'Garment Type',
    quantity: 'Quantity',
    orderSummary: 'Order Summary',
    measurements: 'Measurements (Inches)',
    designAndStyle: 'Design & Style Options',
    specialNotes: 'Special Instructions / Tailoring Notes',
    cabinetSlot: 'Cabinet / Slot Tag',
    saveOrder: 'Save Order',
    saveAndPrint: 'Save & Print Slip',
    loadCustomerMeasurements: 'Load previous measurements',
    existingCustomerFound: 'Existing customer identified! Measurements ready.',
    newCustomerAutoSaved: 'New customer will be automatically added to directory.',
    quickFill: 'Quick Fill',

    perahanTunban: 'Perahan Tunban (Afghan Suit)',
    waistcoat: 'Waistcoat (Wasqat)',
    suit: 'Suit (Drishi)',
    coatKorti: 'Coat / Jacket (Korti)',
    kameezShalwar: 'Kameez Shalwar',
    kurta: 'Kurta',
    otherGarment: 'Custom Garment',

    qad: 'Length (Qad / قد)',
    shana: 'Shoulder (Shana / شانه)',
    asteen: 'Sleeve (Asteen / آستین)',
    yakhan: 'Collar/Neck (Yakhan / یخن)',
    chati: 'Chest (Chati / چاتی)',
    baghal: 'Armpit (Baghal / بغل)',
    kamar: 'Waist (Kamar / کمر)',
    daman: 'Daman / Hem (دامن)',
    tunban: 'Trouser Length (تنبان)',
    pacha: 'Bottom / Pacha (پاچه)',
    surin: 'Seat / Hip (سورین)',
    machDast: 'Wrist (مچ دست)',
    unitInches: 'in',

    customersList: 'Customer Directory',
    customerProfile: 'Customer Profile',
    totalOrdersCount: 'Total Orders',
    lastOrderDate: 'Last Order',
    savedMeasurements: 'Saved Measurements',
    createNewOrderForCustomer: 'New Order with These Measurements',
    customerHistory: 'Order History',
    searchCustomersPlaceholder: 'Search by Customer Name, Phone, or Order #...',
    addNewCustomer: 'Add Customer',
    editCustomer: 'Edit Customer',

    designTemplates: 'Design Templates & Styles',
    manageDesignCategories: 'Customize Design Categories & Presets',
    addCategory: 'Add Design Category',
    categoryTitle: 'Category Title',
    addOption: 'Add Style Option',
    optionName: 'Style Option Name',
    measurementSettings: 'Measurement Fields Settings',
    addMeasurementField: 'Add Custom Measurement Field',
    shopProfile: 'Shop Profile & Receipt Info',
    shopName: 'Shop Name',
    shopAddress: 'Shop Address',
    phones: 'Phone Numbers',
    receiptFooter: 'Receipt Footer Text',
    currency: 'Currency Symbol',
    backupAndRestore: 'Backup & Restore Database',
    exportBackup: 'Download JSON Backup',
    importBackup: 'Restore JSON Backup',
    resetDemoData: 'Reset Demo Data',
    backupDescription: 'Export your entire tailor shop database (all orders, customer records, design templates) as a backup file.',

    tailorReceipt: 'Tailoring Receipt & Measurement Slip',
    measurementSlip: 'Measurement Slip',
    billBarcode: 'Order Barcode',
    phoneBarcode: 'Contact Barcode',
    item: 'Item',
    qty: 'Qty',
    price: 'Price',
    thankYouMessage: 'Thank you for choosing our tailor shop!',

    loginTitle: 'Sign In to Rayan Tailors',
    loginSubtitle: 'Enter your credentials to access the management portal',
    email: 'Email Address',
    password: 'Password',
    signInBtn: 'Sign In',
    signOut: 'Sign Out',
    invalidCredentials: 'Invalid email or password. Please check your credentials.',
    quickLoginAdmin: 'Autofill Admin Login',
    loggedInAs: 'Signed in as',
    adminAccount: 'Master Tailor Admin',
  },

  fa: {
    appName: 'مدیریت خیاطی رایان',
    appSubtitle: 'سیستم جامع مدیریت سفارشات، اندازه‌ها و مشتریان',
    save: 'ذخیره',
    cancel: 'انصراف',
    delete: 'حذف',
    edit: 'ویرایش',
    close: 'بستن',
    search: 'جستجو',
    searchPlaceholder: 'جستجو بر اساس شماره فرمایش، نام مشتری یا شماره تماس...',
    filter: 'فیلتر',
    all: 'همه',
    actions: 'عملیات',
    print: 'چاپ بل / رسید',
    downloadPdf: 'دانلود PDF',
    shareWhatsApp: 'ارسال به واتساپ',
    status: 'وضعیت',
    date: 'تاریخ',
    deliveryDate: 'تاریخ تحویل / تسلیمی',
    returnDate: 'تاریخ واپسی',
    created: 'ثبت شده',
    notes: 'یادداشت‌ها',
    details: 'جزئیات',
    back: 'بازگشت',
    yes: 'بله',
    no: 'نخیر',
    loading: 'در حال بارگذاری...',
    success: 'موفقانه انجام شد',
    savedSuccessfully: 'با موفقیت ذخیره شد',
    deletedSuccessfully: 'با موفقیت حذف شد',
    confirmDelete: 'آیا از حذف این مورد اطمینان دارید؟',
    areYouSure: 'این عمل غیرقابل برگشت می‌باشد.',
    noDataFound: 'هیچ ریکاردی یافت نشد',
    viewDetails: 'مشاهده جزئیات',
    required: 'ضروری',
    optional: 'اختیاری',

    dashboard: 'داشبورد فرمایشات',
    newOrder: 'ثبت فرمایش جدید',
    customers: 'فهرست مشتریان',
    designAndSettings: 'طرح‌ها و تنظیمات',
    designTemplatesNav: 'طرح‌ها و مدل‌ها',
    measurementSettingsNav: 'فیلدهای اندازه',
    shopProfileNav: 'مشخصات خیاطی و بل',
    backupNav: 'پشتیبان‌گیری دیتا',
    menu: 'منوی اصلی',

    totalOrders: 'مجموع فرمایشات',
    pendingOrders: 'در انتظار',
    inProgressOrders: 'در حال دوخت',
    readyOrders: 'آماده تحویل',
    deliveredOrders: 'تحویل داده شده',
    totalRevenue: 'مجموع ارزش',
    totalPaid: 'مجموع وصولی',
    totalBalanceDue: 'باقیمانده کل',

    statusPending: 'در انتظار',
    statusInProgress: 'در حال دوخت',
    statusReady: 'آماده تحویل',
    statusDelivered: 'تحویل شده',

    paymentStatus: 'وضعیت پرداخت',
    paid: 'تکمیل پرداخت شده',
    partial: 'پیش پرداخت (باقیدار)',
    unpaid: 'پرداخت نشده',
    totalAmount: 'جمله مبلغ',
    paidAmount: 'جمله پرداخت (رسید)',
    balanceRemaining: 'جمله باقیات (باقیمانده)',
    advancePayment: 'پیش پرداخت',
    updatePayment: 'تغییر پرداخت',

    customerInfo: 'معلومات مشتری',
    customerName: 'نام مشتری',
    contactNumber: 'شماره تماس',
    whatsappNumber: 'شماره واتساپ',
    orderNumber: 'شماره فرمایش (بل)',
    autoGenerated: 'اتوماتیک',
    garmentType: 'نوع لباس',
    quantity: 'تعداد (دانه/دست)',
    orderSummary: 'خلاصه فرمایش',
    measurements: 'اندازه‌گیری‌ها (انچ)',
    designAndStyle: 'طرح، مدل و استایل',
    specialNotes: 'توضیحات و فرمایشات خاص خیاطی',
    cabinetSlot: 'کابین / الماری',
    saveOrder: 'ذخیره فرمایش',
    saveAndPrint: 'ذخیره و چاپ بل',
    loadCustomerMeasurements: 'بارگذاری اندازه‌های قبلی این مشتری',
    existingCustomerFound: 'مشتری قبلی شناسایی شد! اندازه‌ها آماده بارگذاری هستند.',
    newCustomerAutoSaved: 'مشتری جدید به صورت خودکار به لیست مشتریان اضافه می‌شود.',
    quickFill: 'پر کردن سریع',

    perahanTunban: 'پیراهن و تنبان',
    waistcoat: 'واسکت',
    suit: 'دریشی / دریشی رسمی',
    coatKorti: 'کورتۍ / بالاپوش',
    kameezShalwar: 'قمیص شلوار',
    kurta: 'کورته',
    otherGarment: 'لباس متفرقه',

    qad: 'قد',
    shana: 'شانه',
    asteen: 'آستین',
    yakhan: 'یخن / کالر',
    chati: 'چاتی (سینه)',
    baghal: 'بغل',
    kamar: 'کمر',
    daman: 'دامن',
    tunban: 'تنبان',
    pacha: 'پاچه',
    surin: 'سورین',
    machDast: 'مچ دست',
    unitInches: 'انچ',

    customersList: 'فهرست مشتریان',
    customerProfile: 'پروفایل مشتری',
    totalOrdersCount: 'تعداد کل فرمایشات',
    lastOrderDate: 'آخرین فرمایش',
    savedMeasurements: 'اندازه‌های ثبت شده',
    createNewOrderForCustomer: 'فرمایش جدید با این اندازه‌ها',
    customerHistory: 'تاریخچه فرمایشات',
    searchCustomersPlaceholder: 'جستجو با نام، شماره تماس یا شماره فرمایش...',
    addNewCustomer: 'افزودن مشتری جدید',
    editCustomer: 'ویرایش مشتری',

    designTemplates: 'طرح‌ها و مدل‌های دوخت',
    manageDesignCategories: 'مدیریت و افزودن انواع استایل و مدل‌ها',
    addCategory: 'افزودن دسته استایل',
    categoryTitle: 'عنوان دسته استایل',
    addOption: 'افزودن گزینه مدل',
    optionName: 'نام مدل / طرح',
    measurementSettings: 'تنظیمات فیلدهای اندازه',
    addMeasurementField: 'افزودن فیلد اندازه جدید',
    shopProfile: 'مشخصات خیاطی و سربرگ بل',
    shopName: 'نام خیاطی',
    shopAddress: 'آدرس خیاطی',
    phones: 'شماره‌های تماس',
    receiptFooter: 'متن پایانی بل',
    currency: 'واحد پول',
    backupAndRestore: 'پشتیبان‌گیری و بازگردانی دیتا',
    exportBackup: 'دانلود فایل پشتیبان (JSON)',
    importBackup: 'بازگردانی فایل پشتیبان',
    resetDemoData: 'بارگذاری اطلاعات نمونه',
    backupDescription: 'از تمام سفارشات، مشتریان، اندازه‌ها و مدل‌ها نسخه پشتیبان دریافت کنید.',

    tailorReceipt: 'بل و ورق اندازه خیاطی',
    measurementSlip: 'ورق اندازه',
    billBarcode: 'بارکود بل',
    phoneBarcode: 'بارکود شماره',
    item: 'لباس',
    qty: 'تعداد',
    price: 'قیمت',
    thankYouMessage: 'از انتخاب و اعتماد شما متشکریم!',

    loginTitle: 'ورود به مدیریت خیاطی رایان',
    loginSubtitle: 'برای دسترسی به سیستم، مشخصات خود را وارد نمایید',
    email: 'آدرس ایمیل',
    password: 'رمز عبور (پسورد)',
    signInBtn: 'ورود به سیستم',
    signOut: 'خروج از حساب',
    invalidCredentials: 'ایمیل یا رمز عبور وارد شده نادرست است.',
    quickLoginAdmin: 'تکمیل خودکار اطلاعات مدیر',
    loggedInAs: 'وارد شده به عنوان',
    adminAccount: 'حساب مدیر خیاطی رایان',
  },

  ps: {
    appName: 'د رایان خیاطۍ مدیریت',
    appSubtitle: 'د فرمایشونو، اندازو او پیرودونکو د مدیریت جامع سیستم',
    save: 'ساتل / ثبت',
    cancel: 'ردول',
    delete: 'ړنګول',
    edit: 'سمول',
    close: 'بندول',
    search: 'پلټنه',
    searchPlaceholder: 'د فرمایش شمېرې، نوم یا ټلیفون پر بنسټ پلټنه...',
    filter: 'فلټر',
    all: 'ټول',
    actions: 'کړنې',
    print: 'د بِل چاپ',
    downloadPdf: 'د پی ډي ایف ډاونلوډ',
    shareWhatsApp: 'واټساپ ته لېږل',
    status: 'حالت',
    date: 'نېټه',
    deliveryDate: 'د تسلیمۍ نېټه',
    returnDate: 'د واپسی نېټه',
    created: 'جوړ شوی',
    notes: 'یادښتونه',
    details: 'تفصیلات',
    back: 'شاته',
    yes: 'هو',
    no: 'نه',
    loading: 'د بارېدو په حال کې...',
    success: 'په بریالیتوب سره وشو',
    savedSuccessfully: 'په بریالیتوب سره ثبت شو',
    deletedSuccessfully: 'په بریالیتوب سره ړنګ شو',
    confirmDelete: 'ایا غواړئ دا ریکارډ ړنګ کړئ؟',
    areYouSure: 'دا عمل بېرته نه ګرځي.',
    noDataFound: 'هیڅ ریکارډ ونه موندل شو',
    viewDetails: 'تفصیل کتل',
    required: 'اړین',
    optional: 'اختیاري',

    dashboard: 'د فرمایشونو ډشبورډ',
    newOrder: 'نوی فرمایش',
    customers: 'د پېرودونکو لړلیک',
    designAndSettings: 'ډیزاینونه او تنظیمات',
    designTemplatesNav: 'ډیزاینونه او بېلګې',
    measurementSettingsNav: 'د اندازو فیلډونه',
    shopProfileNav: 'د هټۍ مشخصات او بِل',
    backupNav: 'بیک اپ او ساتنه',
    menu: 'اصلي مینو',

    totalOrders: 'ټول فرمایشونه',
    pendingOrders: 'په تمه',
    inProgressOrders: 'تر کار لاندې',
    readyOrders: 'چمتو شوي',
    deliveredOrders: 'تسلیم شوي',
    totalRevenue: 'ټول ارزښت',
    totalPaid: 'ترلاسه شوې روپۍ',
    totalBalanceDue: 'ټولې پاتې روپۍ',

    statusPending: 'په تمه',
    statusInProgress: 'تر ګنډلو لاندې',
    statusReady: 'چمتو شوی',
    statusDelivered: 'تسلیم شوی',

    paymentStatus: 'د پیسو حالت',
    paid: 'بشپړ ورکړل شوی',
    partial: 'بیعانه (پاتې لری)',
    unpaid: 'نه دی ورکړل شوی',
    totalAmount: 'جمله روپۍ',
    paidAmount: 'جمله پرداخت (رسید)',
    balanceRemaining: 'جمله باقیات (پاتې)',
    advancePayment: 'بیعانه / مخکې ورکړه',
    updatePayment: 'د پیسو بدلون',

    customerInfo: 'د پېرودونکي معلومات',
    customerName: 'د پېرودونکي نوم',
    contactNumber: 'د اړیکې شمېره',
    whatsappNumber: 'د واټساپ شمېره',
    orderNumber: 'د بِل / فرمایش شمېره',
    autoGenerated: 'اتومات',
    garmentType: 'د جامو ډول',
    quantity: 'تعداد (جوړه/دانه)',
    orderSummary: 'د فرمایش لنډیز',
    measurements: 'اندازې (انچ)',
    designAndStyle: 'ډیزاین، استایل او شیپ',
    specialNotes: 'د خیاطۍ ځانګړي یادښتونه',
    cabinetSlot: 'المارۍ / کابین',
    saveOrder: 'فرمایش ثبت کړئ',
    saveAndPrint: 'ثبت او بِل چاپ کړئ',
    loadCustomerMeasurements: 'د دې مشتري پخوانۍ اندازې راواخلئ',
    existingCustomerFound: 'پخوانی مشتري وپېژندل شو! اندازې چمتو دي.',
    newCustomerAutoSaved: 'نوی مشتري به په اتومات ډول د پیرودونکو لړۍ ته اضافه شي.',
    quickFill: 'چټک ډکول',

    perahanTunban: 'پیراهن او تنبان (ګنډل شوې جامې)',
    waistcoat: 'واسکت',
    suit: 'دریشي / رسمي کالي',
    coatKorti: 'کورتۍ / واسکټ کوټ',
    kameezShalwar: 'قمیص شلوار',
    kurta: 'کورته',
    otherGarment: 'نورې جامې',

    qad: 'قد',
    shana: 'شانه',
    asteen: 'آستین',
    yakhan: 'یخن / کالر',
    chati: 'چاتی (سینه)',
    baghal: 'بغل',
    kamar: 'کمر',
    daman: 'دامن',
    tunban: 'تنبان / پرتوګ',
    pacha: 'پاچه',
    surin: 'سورین',
    machDast: 'مچ لاس',
    unitInches: 'انچ',

    customersList: 'د پېرودونکو لړلیک',
    customerProfile: 'د مشتري پېژندنه',
    totalOrdersCount: 'د فرمایشونو شمېر',
    lastOrderDate: 'وروستی فرمایش',
    savedMeasurements: 'ساتل شوې اندازې',
    createNewOrderForCustomer: 'په دې اندازو نوی فرمایش',
    customerHistory: 'د فرمایشونو تاریخچه',
    searchCustomersPlaceholder: 'د نوم، ټلیفون یا فرمایش نمبر له مخې پلټنه...',
    addNewCustomer: 'نوی مشتري ورزیات کړئ',
    editCustomer: 'مشتري سم کړئ',

    designTemplates: 'ډیزاینونه او بېلګې',
    manageDesignCategories: 'د ډیزاینونو او استایلونو مدیریت',
    addCategory: 'د ډیزاین نوې برخه',
    categoryTitle: 'د برخې نوم',
    addOption: 'د موډل اختیار',
    optionName: 'د موډل / استایل نوم',
    measurementSettings: 'د اندازو فیلډونه',
    addMeasurementField: 'د نوې اندازې فیلډ',
    shopProfile: 'د هټۍ مشخصات او د بِل سرلیک',
    shopName: 'د خیاطۍ نوم',
    shopAddress: 'د خیاطۍ پته',
    phones: 'د اړیکې شمېرې',
    receiptFooter: 'د بِل پایلیک',
    currency: 'د پیسو واحد',
    backupAndRestore: 'بیک اپ او د معلوماتو ساتنه',
    exportBackup: 'د بیک اپ ډاونلوډ (JSON)',
    importBackup: 'د بیک اپ بېرته راوستل',
    resetDemoData: 'نمونه معلومات راوستل',
    backupDescription: 'د ټولو فرمایشونو، پېرودونکو، اندازو او ډیزاینونو بیک اپ فایل ترلاسه کړئ.',

    tailorReceipt: 'د خیاطۍ بِل او د اندازې پرچه',
    measurementSlip: 'د اندازې پرچه',
    billBarcode: 'د بِل بارکوډ',
    phoneBarcode: 'د ټلیفون بارکوډ',
    item: 'کالي',
    qty: 'تعداد',
    price: 'قیمت',
    thankYouMessage: 'ستاسو له باور او راتګ څخه مننه!',

    loginTitle: 'د رایان خیاطۍ مدیریت ته ننوتل',
    loginSubtitle: 'سیستم ته د لاسرسي لپاره خپل معلومات دننه کړئ',
    email: 'د بریښنالیک پته',
    password: 'پټنوم (پاسورډ)',
    signInBtn: 'سیستم ته ننوتل',
    signOut: 'له حساب څخه وتل',
    invalidCredentials: 'بریښنالیک یا پټنوم ناسم دی. مهرباني وکړئ معلومات وګورئ.',
    quickLoginAdmin: 'د اډمین معلومات اتومات ډکول',
    loggedInAs: 'ننوتلی یاست لکه',
    adminAccount: 'د رایان خیاطۍ د مدیر حساب',
  },
};
